services:
  # PostgreSQL Database
  - type: pserv
    name: sangeet-restaurant-db
    env: node
    plan: free
    region: oregon
    databases:
      - name: sangeet_restaurant
        user: sangeet_user

  # Backend Web Service
  - type: web
    name: sangeet-restaurant-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: sangeet-restaurant-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
